package com.barrett.aialertservice.config;

/**
 * @program: smartsite-master
 * @description: Use this configuration to add static resource generated by swaggerUI to the default springboot resource
 * folder, thus the swaggerUI webpage for apis can be properly visited.
 * @author: Barrett
 * @create: 2020-07-02 10:32
 **/

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

@Configuration
class WebMvcConfig implements WebMvcConfigurer {

    private static final String[] CLASSPATH_RESOURCE_LOCATIONS = {"classpath:/static/", "classpath:/public/"};

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");

        // Add below property for hystrix dashboard (static content available in hystrix-dashboard jar)
        registry.addResourceHandler("/").addResourceLocations(CLASSPATH_RESOURCE_LOCATIONS);
    }
}
